package galen.pages.tenant.dx.InitialAssessment;

import galen.pages.common.DocAttestationNo;
import galen.pages.common.GalenPageObj;
import org.openqa.selenium.WebDriver;

public class DxPageObj extends GalenPageObj {
    public Numbers numbers;
    public UsedProduct usedProduct;
    public OrderForSelf orderForSelf;
    public Smoking smoking;
    public SmokingDisclaimer smokingDisclaimer;
    public Menstrual menstrual;
    public EverHadCancer everHadCancer;
    public CancerList cancerList;
    public BloodPressureMeds bloodPressureMeds;
    public BirthYear birthYear;
    public BirthControl birthControl;
    public BirthControlB birthControlB;
    public PreventPregnancy pregnancy;
    public Antifungal antifungal;
    public AntifungalMeds antifungalMeds;
    public BloodClot bloodClot;
    public CardiacRisk cardiacRisk;
    public BreastFeeding breastFeeding;
    public DDICondition ddiCondition;
    public DDIHepC ddiHepC;
    public DDIEpBipolar ddiEpBipolar;
    public DDIThyroid ddiThyroid;
    public DDIHIV ddihiv;
    public DDIHighCholesterol ddiHighCholesterol;
    public Depression depression;
    public DiagnosedDepression diagnosedDepression;
    public Diabetes diabetes;
    public ReviewAnswers review;
    public ADBU adbu;
    public ADBUBP adbubpScreen;
    public ADBUBPNormal adbubpNormal;
    public ADBUBC adbuddi;
    public EnterBP enterBP;
    public EnterBPEnd enterBPEnd;
    public Gallbladder gallbladder;
    public IrregularHeartBeat irregularHeartBeat;
    public KnowBPNumber knowBPNumber;
    public LiverCancer liverCancer;
    public Migraines migraines;
    public OAuthPostReview oAuthPostReview;
    public ObesityBMI obesity;
    public OtherMedication otherMedication;
    public PurchaseOptions purchaseOptions;
    public PregnancyLoss pregnancyLoss;
    public Pregnant pregnant;
    public VaginalBleeding vaginalBleeding;
    public WelcomePage welcomePage;
    public DocAttestationNo docAttestationNo;

    public DxPageObj(WebDriver driver) {
        super(driver);
        welcomePage = new WelcomePage(driver);
        numbers = new Numbers(driver);
        usedProduct = new UsedProduct(driver);
        orderForSelf = new OrderForSelf(driver);
        pregnancy = new PreventPregnancy(driver);
        smoking = new Smoking(driver);
        birthYear = new BirthYear(driver);
        smokingDisclaimer = new SmokingDisclaimer(driver);
        menstrual = new Menstrual(driver);
        everHadCancer = new EverHadCancer(driver);
        cancerList = new CancerList(driver);
        bloodPressureMeds = new BloodPressureMeds(driver);
        birthControl = new BirthControl(driver);
        birthControlB = new BirthControlB(driver);
        liverCancer = new LiverCancer(driver);
        cardiacRisk = new CardiacRisk(driver);
        bloodClot = new BloodClot(driver);
        ddiCondition = new DDICondition(driver);
        ddiHepC = new DDIHepC(driver);
        ddiEpBipolar = new DDIEpBipolar(driver);
        ddihiv = new DDIHIV(driver);
        ddiThyroid = new DDIThyroid(driver);
        ddiHighCholesterol = new DDIHighCholesterol(driver);
        antifungal = new Antifungal(driver);
        antifungalMeds = new AntifungalMeds(driver);
        diabetes = new Diabetes(driver);
        irregularHeartBeat = new IrregularHeartBeat(driver);
        pregnant = new Pregnant(driver);
        breastFeeding = new BreastFeeding(driver);
        pregnancyLoss = new PregnancyLoss(driver);
        migraines = new Migraines(driver);
        obesity = new ObesityBMI(driver);
        otherMedication = new OtherMedication(driver);
        gallbladder = new Gallbladder(driver);
        depression = new Depression(driver);
        diagnosedDepression = new DiagnosedDepression(driver);
        knowBPNumber = new KnowBPNumber(driver);
        enterBP = new EnterBP(driver);
        review = new ReviewAnswers(driver);
        oAuthPostReview = new OAuthPostReview(driver);
        adbu = new ADBU(driver);
        adbuddi= new ADBUBC(driver);
        adbubpScreen = new ADBUBP(driver);
        adbubpNormal = new ADBUBPNormal(driver);
        enterBPEnd = new EnterBPEnd(driver);
        docAttestationNo = new DocAttestationNo(driver);
        purchaseOptions = new PurchaseOptions(driver);
        vaginalBleeding = new VaginalBleeding(driver);
    }
}
