package galen.pages.tenant.petros.InitialAssessment;

import galen.pages.common.DocAttestationNo;
import galen.pages.common.GalenPageObj;
import galen.pages.common.PritUnlPage;
import galen.pages.common.PrivacyPage;
import org.openqa.selenium.WebDriver;

public class PetrosPageObj extends GalenPageObj {
    public WelcomePage welcomePage;
    public PrivacyPage privacyPage;
    public SexAndBirthYear sexAndBirthYear;
    public PurchaseSelf purchaseSelf;
    public ErectileDysfunction erectileDysfunction;
    public SHIM_QuestionnaireIntroduction questionnaireIntroduction;
    public SHIM_Questionnaire_1 questionnaire1;
    public SHIM_Questionnaire_2 questionnaire2;
    public SHIM_Questionnaire_3 questionnaire3;
    public SHIM_Questionnaire_4 questionnaire4;
    public SHIM_Questionnaire_5 questionnaire5;
    public ADOPBU_OtherED_Meds otherEDMeds;
    public NitrateUse nitrateUse;
    public NotPurchasingSelfScreen notPurchasingSelfScreen;
    public ClarificationOnNitrateUse clarification;
    public NitratePoppersUse nitratePoppersUse;
    public  ClarificationOnPoppers clarificationOnPoppers;
    public HeartProblemsInstructional heartProblemsInstruction;
    public HeartNotSafeForSex heartNotSafeForSex;
    public ADBU_CardiacConditions_1 cardiacConditions1;
    public HeartFailure heartFailure;
    public ADBU_CardiacConditions_2 cardiacConditions2;
    public ADBU_CardiacConditions_3 cardiacConditions3;
    public ADBU_CardiacConditions_4 cardiacConditions4;
    public PulmonaryHypertensionsMedicine hypertensionsMedicine;
    public ADOPBU_HighBloodPressureMedicines highBloodPressureMedicines;
    public Antifungals antifungals;
    public Antibiotics antibiotics;
    public Antidepressants antidepressants;
    public HIVMedicines hivMedicines;
    public NoncardiacHealthConditions noncardiacHealthConditions;
    public NoncardiacAllergicReactions noncardiacAllergicReactions;
    public ADBU_ErectionLongerThan4Hours erectionLongerThan4Hours;
    public ADBU_NoncardiacConditions_1 noncardiacConditions1;
    public ADBU_PeyroniesDisease peyroniesDisease;
    public ADBU_NoncardiacConditions_2 noncardiacConditions2;
    public ADBU_NoncardiacConditions_3 noncardiacConditions3;
    public ADOPBU_EnlargedProstateMedicine enlargedProstateMedicine;
    public ED_AndHeartDiseaseInfo edAndHeartDiseaseInfo;
    public ADOPBU_OnceADayInstruction onceADayInstruction;
    public ReviewAnswers review;
    public ADOPBU adopbu;
    public ADBU adbu;
    public DocAttestationNo docAttestationNo;

    public PetrosPageObj(WebDriver driver)  {
        super(driver);
        pritUnl = new PritUnlPage(driver);
        welcomePage=new WelcomePage(driver);
        privacyPage=new PrivacyPage(driver);
        onceADayInstruction= new ADOPBU_OnceADayInstruction(driver);
        sexAndBirthYear = new SexAndBirthYear(driver);
        purchaseSelf = new PurchaseSelf(driver);
        erectileDysfunction =new ErectileDysfunction(driver);
        questionnaireIntroduction = new SHIM_QuestionnaireIntroduction(driver);
        questionnaire1 = new SHIM_Questionnaire_1(driver);
        questionnaire2 = new SHIM_Questionnaire_2(driver) ;
        questionnaire3 = new SHIM_Questionnaire_3(driver) ;
        questionnaire4 = new SHIM_Questionnaire_4(driver) ;
        questionnaire5 = new SHIM_Questionnaire_5(driver) ;
        otherEDMeds=new ADOPBU_OtherED_Meds(driver);
        nitrateUse = new NitrateUse(driver);
        notPurchasingSelfScreen=new NotPurchasingSelfScreen(driver);
        clarification = new ClarificationOnNitrateUse(driver) ;
        nitratePoppersUse = new NitratePoppersUse(driver);
        clarificationOnPoppers = new ClarificationOnPoppers(driver);
        heartProblemsInstruction = new HeartProblemsInstructional(driver);
        heartNotSafeForSex = new HeartNotSafeForSex(driver);
        cardiacConditions1 = new ADBU_CardiacConditions_1(driver);
        heartFailure = new HeartFailure(driver);
        cardiacConditions2 = new ADBU_CardiacConditions_2(driver);
        cardiacConditions3 = new ADBU_CardiacConditions_3(driver);
        cardiacConditions4 = new ADBU_CardiacConditions_4(driver);
        hypertensionsMedicine = new PulmonaryHypertensionsMedicine(driver);
        highBloodPressureMedicines = new ADOPBU_HighBloodPressureMedicines(driver);
        antifungals= new Antifungals(driver) ;
        antibiotics = new Antibiotics(driver) ;
        antidepressants = new Antidepressants(driver);
        hivMedicines = new HIVMedicines(driver) ;
        noncardiacHealthConditions = new NoncardiacHealthConditions(driver);
        noncardiacAllergicReactions = new NoncardiacAllergicReactions(driver);
        erectionLongerThan4Hours = new ADBU_ErectionLongerThan4Hours(driver);
        noncardiacConditions1 = new ADBU_NoncardiacConditions_1(driver);
        peyroniesDisease = new ADBU_PeyroniesDisease(driver);
        noncardiacConditions2 = new ADBU_NoncardiacConditions_2(driver);
        noncardiacConditions3 = new ADBU_NoncardiacConditions_3(driver);
        enlargedProstateMedicine = new ADOPBU_EnlargedProstateMedicine(driver);
        edAndHeartDiseaseInfo= new ED_AndHeartDiseaseInfo(driver) ;
        review= new ReviewAnswers(driver);
        adopbu = new ADOPBU(driver);
        adbu = new ADBU(driver);
        docAttestationNo = new DocAttestationNo(driver);
    }
}
